### ISSUE TITLE
Convert time into mm:ss:ms...

### ISSUE THREAD

**Issue by NotMyTschopp** [NotMyTschopp/Alpha-vTschopp#2]
...and show it on screen.

**Comment by smeerws** [comment]
add to StopWatch.cs in Update after timer += Time.deltaTime;

 watch.text = string.Format("{0:00}:{1:00}.{2:00}",
                     Mathf.Floor(timer / 60),//minutes
                     Mathf.Floor(timer) % 60,//seconds
                     Mathf.Floor((timer * 100) % 100));//centiseconds

**Comment by NotMyTschopp** [comment]
Thanks! 70edc0b2a93b19f5128c7613e6694bb3518566cf
